# Generated by Django 3.0.5 on 2020-04-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200422_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
