# Generated by Django 3.0.5 on 2020-05-05 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200504_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otvet',
            name='stimul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Stimul_slov'),
        ),
    ]
