# Generated by Django 3.0.5 on 2020-05-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='stimul',
            field=models.ManyToManyField(to='survey.Stimul_slov'),
        ),
    ]
