# Generated by Django 3.0.5 on 2020-05-08 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_answer_stimul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='stimul',
        ),
        migrations.AddField(
            model_name='answer',
            name='stimul',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Stimul_slov'),
            preserve_default=False,
        ),
    ]
