# Generated by Django 3.0.5 on 2020-04-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20200425_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='fullname',
        ),
    ]
