# Generated by Django 3.0.5 on 2020-04-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_profil_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otvet',
            name='user',
        ),
    ]
