# Generated by Django 3.0.5 on 2020-05-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200508_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='stimul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Stimul_slov'),
        ),
    ]
